package com.example.creator.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FilterChip
import androidx.compose.material3.FilterChipDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Surface
import androidx.compose.material3.Switch
import androidx.compose.material3.SwitchDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.model.CreatorContentEntity
import com.example.ui.theme.NexoraCyanAccent
import com.example.ui.theme.NexoraErrorRed
import com.example.ui.theme.NexoraSurfaceBorder
import com.example.ui.theme.NexoraSurfaceDark
import com.example.ui.theme.NexoraTextMuted
import com.example.ui.theme.NexoraTextPrimary
import com.example.ui.theme.NexoraTextSecondary

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EditContentDetailsDialog(
    content: CreatorContentEntity,
    onDismiss: () -> Unit,
    onSave: (
        title: String,
        description: String,
        hashtags: String,
        visibility: String,
        isMadeForKids: Boolean,
        location: String?,
        allowComments: Boolean,
        category: String,
        playlist: String?,
        isAiGenerated: Boolean
    ) -> Unit
) {
    var title by remember { mutableStateOf(content.title) }
    var description by remember { mutableStateOf(content.description) }
    var hashtags by remember { mutableStateOf(content.hashtags) }
    var visibility by remember { mutableStateOf(content.visibility) }
    var isMadeForKids by remember { mutableStateOf(content.isMadeForKids) }
    var location by remember { mutableStateOf(content.location ?: "") }
    var allowComments by remember { mutableStateOf(content.allowComments) }
    var category by remember { mutableStateOf(content.category) }
    var playlist by remember { mutableStateOf(content.playlist ?: "") }
    var isAiGenerated by remember { mutableStateOf(content.isAiGenerated) }

    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = NexoraSurfaceDark,
        titleContentColor = NexoraTextPrimary,
        textContentColor = NexoraTextSecondary,
        title = {
            Text("Edit Video Details", fontWeight = FontWeight.Bold)
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                OutlinedTextField(
                    value = title,
                    onValueChange = { title = it },
                    label = { Text("Title") },
                    singleLine = true,
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = NexoraTextPrimary,
                        unfocusedTextColor = NexoraTextPrimary
                    )
                )

                OutlinedTextField(
                    value = description,
                    onValueChange = { description = it },
                    label = { Text("Description") },
                    minLines = 2,
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = NexoraTextPrimary,
                        unfocusedTextColor = NexoraTextPrimary
                    )
                )

                OutlinedTextField(
                    value = hashtags,
                    onValueChange = { hashtags = it },
                    label = { Text("Hashtags") },
                    singleLine = true,
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = NexoraTextPrimary,
                        unfocusedTextColor = NexoraTextPrimary
                    )
                )

                Text("Visibility", style = MaterialTheme.typography.labelSmall, color = NexoraCyanAccent)
                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    listOf("PUBLIC", "UNLISTED", "PRIVATE").forEach { v ->
                        FilterChip(
                            selected = visibility == v,
                            onClick = { visibility = v },
                            label = { Text(v, fontSize = 11.sp) },
                            colors = FilterChipDefaults.filterChipColors(
                                selectedContainerColor = NexoraCyanAccent,
                                selectedLabelColor = Color.Black
                            )
                        )
                    }
                }

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("Made for Kids", color = NexoraTextPrimary, fontSize = 13.sp)
                    Switch(
                        checked = isMadeForKids,
                        onCheckedChange = { isMadeForKids = it },
                        colors = SwitchDefaults.colors(checkedThumbColor = Color.Black, checkedTrackColor = NexoraCyanAccent)
                    )
                }

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("Allow Comments", color = NexoraTextPrimary, fontSize = 13.sp)
                    Switch(
                        checked = allowComments,
                        onCheckedChange = { allowComments = it },
                        colors = SwitchDefaults.colors(checkedThumbColor = Color.Black, checkedTrackColor = NexoraCyanAccent)
                    )
                }

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("AI-Generated Content", color = NexoraTextPrimary, fontSize = 13.sp)
                    Switch(
                        checked = isAiGenerated,
                        onCheckedChange = { isAiGenerated = it },
                        colors = SwitchDefaults.colors(checkedThumbColor = Color.Black, checkedTrackColor = NexoraCyanAccent)
                    )
                }

                OutlinedTextField(
                    value = category,
                    onValueChange = { category = it },
                    label = { Text("Category") },
                    singleLine = true,
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = NexoraTextPrimary,
                        unfocusedTextColor = NexoraTextPrimary
                    )
                )

                OutlinedTextField(
                    value = playlist,
                    onValueChange = { playlist = it },
                    label = { Text("Playlist") },
                    singleLine = true,
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = NexoraTextPrimary,
                        unfocusedTextColor = NexoraTextPrimary
                    )
                )

                OutlinedTextField(
                    value = location,
                    onValueChange = { location = it },
                    label = { Text("Location") },
                    singleLine = true,
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedTextColor = NexoraTextPrimary,
                        unfocusedTextColor = NexoraTextPrimary
                    )
                )
            }
        },
        confirmButton = {
            TextButton(
                onClick = {
                    onSave(
                        title, description, hashtags, visibility,
                        isMadeForKids, location.ifBlank { null },
                        allowComments, category, playlist.ifBlank { null },
                        isAiGenerated
                    )
                }
            ) {
                Text("Save Changes", color = NexoraCyanAccent, fontWeight = FontWeight.Bold)
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel", color = NexoraTextSecondary)
            }
        }
    )
}
