package com.example.upload.model

enum class UploadTargetType(
    val title: String,
    val allowsCameraPhoto: Boolean = false,
    val allowsCameraVideo: Boolean = false,
    val allowsGalleryPhotos: Boolean = true,
    val allowsGalleryVideos: Boolean = false,
    val allowsGenericFiles: Boolean = false,
    val requiresCrop: Boolean = false,
    val maxSizeBytes: Long = 20 * 1024 * 1024L,
    val allowedMimeTypes: List<String> = emptyList(),
    val allowedMimePrefixes: List<String> = emptyList(),
    val allowedExtensions: List<String> = emptyList(),
    val targetAspectRatio: Float? = null,
    val maxDurationMs: Long? = null,
    val minDurationMs: Long? = null
) {
    PROFILE_PICTURE(
        title = "Personal Profile Picture",
        allowsCameraPhoto = true,
        allowsCameraVideo = false,
        allowsGalleryPhotos = true,
        allowsGalleryVideos = false,
        allowsGenericFiles = false,
        requiresCrop = true,
        maxSizeBytes = 15 * 1024 * 1024L,
        allowedMimeTypes = listOf("image/jpeg", "image/png", "image/webp", "image/gif"),
        allowedMimePrefixes = listOf("image/"),
        allowedExtensions = listOf("jpg", "jpeg", "png", "webp", "gif"),
        targetAspectRatio = 1.0f
    ),
    CHANNEL_PICTURE(
        title = "Channel Profile Picture",
        allowsCameraPhoto = true,
        allowsCameraVideo = false,
        allowsGalleryPhotos = true,
        allowsGalleryVideos = false,
        allowsGenericFiles = false,
        requiresCrop = true,
        maxSizeBytes = 15 * 1024 * 1024L,
        allowedMimeTypes = listOf("image/jpeg", "image/png", "image/webp", "image/gif"),
        allowedMimePrefixes = listOf("image/"),
        allowedExtensions = listOf("jpg", "jpeg", "png", "webp", "gif"),
        targetAspectRatio = 1.0f
    ),
    CHANNEL_BANNER(
        title = "Channel Banner",
        allowsCameraPhoto = false,
        allowsCameraVideo = false,
        allowsGalleryPhotos = true,
        allowsGalleryVideos = false,
        allowsGenericFiles = false,
        requiresCrop = true,
        maxSizeBytes = 20 * 1024 * 1024L,
        allowedMimeTypes = listOf("image/jpeg", "image/png", "image/webp"),
        allowedMimePrefixes = listOf("image/"),
        allowedExtensions = listOf("jpg", "jpeg", "png", "webp"),
        targetAspectRatio = 16f / 9f
    ),
    LONG_VIDEO(
        title = "Long Video",
        allowsCameraPhoto = false,
        allowsCameraVideo = true,
        allowsGalleryPhotos = false,
        allowsGalleryVideos = true,
        allowsGenericFiles = true,
        requiresCrop = false,
        maxSizeBytes = 2048 * 1024 * 1024L, // 2 GB
        allowedMimeTypes = listOf("video/mp4", "video/quicktime", "video/webm", "video/x-matroska", "video/3gpp"),
        allowedMimePrefixes = listOf("video/"),
        allowedExtensions = listOf("mp4", "mkv", "mov", "webm", "avi", "3gp"),
        minDurationMs = 3_000L
    ),
    SHORTS(
        title = "Short Video",
        allowsCameraPhoto = false,
        allowsCameraVideo = true,
        allowsGalleryPhotos = false,
        allowsGalleryVideos = true,
        allowsGenericFiles = false,
        requiresCrop = false,
        maxSizeBytes = 500 * 1024 * 1024L, // 500 MB
        allowedMimeTypes = listOf("video/mp4", "video/quicktime", "video/webm", "video/3gpp"),
        allowedMimePrefixes = listOf("video/"),
        allowedExtensions = listOf("mp4", "mov", "webm", "3gp"),
        maxDurationMs = 60_000L
    ),
    SHORT(
        title = "Short Video",
        allowsCameraPhoto = false,
        allowsCameraVideo = true,
        allowsGalleryPhotos = false,
        allowsGalleryVideos = true,
        allowsGenericFiles = false,
        requiresCrop = false,
        maxSizeBytes = 500 * 1024 * 1024L,
        allowedMimeTypes = listOf("video/mp4", "video/quicktime", "video/webm", "video/3gpp"),
        allowedMimePrefixes = listOf("video/"),
        allowedExtensions = listOf("mp4", "mov", "webm", "3gp"),
        maxDurationMs = 60_000L
    ),
    POST_IMAGE(
        title = "Post Image",
        allowsCameraPhoto = true,
        allowsCameraVideo = false,
        allowsGalleryPhotos = true,
        allowsGalleryVideos = false,
        allowsGenericFiles = false,
        requiresCrop = false,
        maxSizeBytes = 25 * 1024 * 1024L,
        allowedMimeTypes = listOf("image/jpeg", "image/png", "image/webp", "image/gif"),
        allowedMimePrefixes = listOf("image/"),
        allowedExtensions = listOf("jpg", "jpeg", "png", "webp", "gif")
    ),
    THUMBNAIL(
        title = "Custom Thumbnail",
        allowsCameraPhoto = true,
        allowsCameraVideo = false,
        allowsGalleryPhotos = true,
        allowsGalleryVideos = false,
        allowsGenericFiles = false,
        requiresCrop = true,
        maxSizeBytes = 10 * 1024 * 1024L,
        allowedMimeTypes = listOf("image/jpeg", "image/png", "image/webp"),
        allowedMimePrefixes = listOf("image/"),
        allowedExtensions = listOf("jpg", "jpeg", "png", "webp"),
        targetAspectRatio = 16f / 9f
    ),
    CUSTOM_THUMBNAIL(
        title = "Custom Thumbnail",
        allowsCameraPhoto = true,
        allowsCameraVideo = false,
        allowsGalleryPhotos = true,
        allowsGalleryVideos = false,
        allowsGenericFiles = false,
        requiresCrop = true,
        maxSizeBytes = 10 * 1024 * 1024L,
        allowedMimeTypes = listOf("image/jpeg", "image/png", "image/webp"),
        allowedMimePrefixes = listOf("image/"),
        allowedExtensions = listOf("jpg", "jpeg", "png", "webp"),
        targetAspectRatio = 16f / 9f
    ),
    GENERIC_FILE(
        title = "File",
        allowsCameraPhoto = false,
        allowsCameraVideo = false,
        allowsGalleryPhotos = false,
        allowsGalleryVideos = false,
        allowsGenericFiles = true,
        requiresCrop = false,
        maxSizeBytes = 500 * 1024 * 1024L,
        allowedMimeTypes = listOf("*/*"),
        allowedMimePrefixes = listOf("application/", "video/", "audio/", "image/", "text/"),
        allowedExtensions = listOf("pdf", "zip", "mp4", "jpg", "png", "txt", "doc", "docx")
    )
}
